### ISSUE TITLE
Alter Index not supporting in babelfish

### ISSUE THREAD

**Issue by JayakumarEMIS** [bill-ramos-rmoswi/babelfish_postgresql_towel#10]
HI @bill-ramos-rmoswi, I can see alter index functionality not support in babelfish, but we have some maintenance procedure will use to rebuild and reorganize the index I mentioned the query below, is there any same equivalent feature available in postgre sql, if it is available i can write in postgre itself?

ALTER INDEX ALL ON [dbo].[Employee] REBUILD WITH (SORT_IN_TEMPDB = ON);
ALTER INDEX ALL ON [dbo].[Employee] REORGANIZE WITH (LOB_COMPACTION = ON);

**Comment by JayakumarEMIS** [comment]
@bill-ramos-rmoswi and @staticlibs, provide your comment for the query?

**Comment by JayakumarEMIS** [comment]
Hi @bill-ramos-rmoswi, I have added below function for rebuild and reorganize index for postgre, jut look a view on it and provide your comments

Rebuild index:
--------------------
CREATE OR REPLACE FUNCTION master_dbo.reindextable(
	tablename text)
    RETURNS void
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
    EXECUTE 'REINDEX TABLE '|| tablename ||';';
END;
$BODY$;

Reorganize index:
---------------------
CREATE OR REPLACE FUNCTION master_dbo.analyzetable(
	tablename text)
    RETURNS void
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
    EXECUTE 'ANALYZE '|| tablename ||';';
END;
$BODY$;

**Comment by JayakumarEMIS** [comment]
Thanks for your suggestions @bill-ramos-rmoswi, I have created function sys schema and gave public access that is working fine, but i have one query i can see all the babelfish related function inside sys schema only, incase, for next babelfish release if they add any function under same name "reindex" will it cause the issue.

CREATE OR REPLACE FUNCTION sys.reindex(tablename text)
RETURNS void
LANGUAGE 'plpgsql'
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$

BEGIN
EXECUTE 'REINDEX TABLE '|| tablename ||';';
END;
$BODY$;

GRANT EXECUTE ON FUNCTION sys.reindex(tablename text) TO PUBLIC;

**Comment by bill-ramos-rmoswi** [comment]
Hi @JayakumarEMIS ,
Personally, I prefer to use functions for processes that don't change data or impact or change system behavior. I'm old school - functions take input, process (no changes to data), and return a result.

In contrast, procedure code can do anything. :-) 

Note, you might type creating the procedure in master with the sp_ prefix. Babelfish should pick it up and run the code like SQL Server.

Also, you will want to pass in the name of the schema for the table. There are metadata tables in Babelfish that map the T-SQL schema to the PostgreSQL schema.


Thanks,
Bill

**Comment by JayakumarEMIS** [comment]
Thanks @bill-ramos-rmoswi, your suggestion would be helpful

**Comment by bill-ramos-rmoswi** [comment]
It's actually ok to alter indexes on a PG connection. You just need to know the mapped Babelfish index to alter it. @staticlibs but together a great Wiki article on the Babelfish repo. I can never recall where the article actually located. :-o

**Comment by staticlibs** [comment]
Yep, [that page](https://github.com/babelfish-for-postgresql/babelfish-for-postgresql/wiki/Long-identifiers) is not trivial to find, there are actually 3 official places for upstream Babelfish documentation now (web-site, GH wiki and Aurora docs).

The following function can be used to get the "physical" Postgres index (or constraint) name:

```tsql
CREATE FUNCTION MangleConstraintOrIndexName(@tableName varchar(128), @icName varchar(128))
RETURNS varchar(63) AS
BEGIN
    RETURN sys.babelfish_truncate_identifier(
        sys.babelfish_truncate_identifier(LOWER(@icName)) +
        sys.babelfish_truncate_identifier(LOWER(@tableName)) +
        md5(sys.babelfish_truncate_identifier(LOWER(@icName))))
END
```
