### ISSUE TITLE
Delete CTE Not supported in babelfish

### ISSUE THREAD

**Issue by JayakumarEMIS** [bill-ramos-rmoswi/babelfish_postgresql_towel#3]
Hi @bill-ramos-rmoswi ,

based on your suggestion for delete cte, if the query is working only when sortorder with code column is unique record, for example if I work below data it will remove all A and B value is removed only C is remains, 
 
![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/153603497/6401847e-2495-4e23-a054-908491108f14)

INSERT INTO [dbo].[groupingTree] ([GroupingId]
      ,[Code]
      ,[Description]
      ,[SortOrder]) VALUES
	  (1, 'B', 'fd', 4),
	  (4, 'A', 'fd', 3),
	  (2, 'B', 'fd', 4),
	  (2, 'A', 'fd', 3),
	  (4, 'B', 'fd', 2),
	  (5, 'C', 'fd', 5)

![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/153603497/29f3f437-b8a6-4d94-95ae-27bec3054d61)

For the scenario, I have added one new solution, seems it is working fine, can you share your opinion on this?

SELECT * into #temp from 
(SELECT *, ROW_NUMBER() OVER(PARTITION BY [Code] ORDER BY [Code] DESC) AS RN
FROM [dbo].[groupingTree]) T where T.RN = 1

TRUNCATE TABLE [dbo].[groupingTree]

INSERT INTO [dbo].[groupingTree]
(
	[GroupingId]
	,[Code]
	,[Description]
	,[SortOrder]
)
SELECT [GroupingId]
	,[Code]
	,[Description]
	,[SortOrder] FROM #temp

DROP TABLE #temp

**Comment by JayakumarEMIS** [comment]
> Hi @bill-ramos-rmoswi ,
> 
> based on your suggestion for delete cte, if the query is working only when sortorder with code column is unique record, for example if I work below data it will remove all A and B value is removed only C is remains,
> 
> ![image](https://private-user-images.githubusercontent.com/153603497/344676141-6401847e-2495-4e23-a054-908491108f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzkzMzEsIm5iZiI6MTcxOTgzOTAzMSwicGF0aCI6Ii8xNTM2MDM0OTcvMzQ0Njc2MTQxLTY0MDE4NDdlLTI0OTUtNGUyMy1hMDU0LTkwODQ5MTEwOGYxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQxMzAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTBhNzRhYTdkNmY0MjU5NTA2Mjg2Y2U3MmE3Y2Y5MDlkOTNkNjMwMmZkMzUxNTlhNTYxNjVjODFjZjRhOWM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c9Hu2xlAWoQjUKN37lOAvYQB7x27HJQCIRj6NXbXKu4)
> 
> INSERT INTO [dbo].[groupingTree] ([GroupingId] ,[Code] ,[Description] ,[SortOrder]) VALUES (1, 'B', 'fd', 4), (4, 'A', 'fd', 3), (2, 'B', 'fd', 4), (2, 'A', 'fd', 3), (4, 'B', 'fd', 2), (5, 'C', 'fd', 5)
> 
> ![image](https://private-user-images.githubusercontent.com/153603497/344677422-29f3f437-b8a6-4d94-95ae-27bec3054d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzkzMzEsIm5iZiI6MTcxOTgzOTAzMSwicGF0aCI6Ii8xNTM2MDM0OTcvMzQ0Njc3NDIyLTI5ZjNmNDM3LWI4YTYtNGQ5NC05NWFlLTI3YmVjMzA1NGQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQxMzAzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjkxM2E1ODdmYjJkMDAwZTkyNmEyZDFhYjA2M2MxZTc4OTdiNmEzYmY5NmM1ZTczZGIzODdlNDhlN2JhYjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bkO8M159c5_G9ehtUNQSUqqYau_dxWjzJvOAA-P6AUc)
> 
> For the scenario, I have added one new solution, seems it is working fine, can you please share your opinion on this?
> 
> SELECT * into #temp from (SELECT *, ROW_NUMBER() OVER(PARTITION BY [Code] ORDER BY [Code] DESC) AS RN FROM [dbo].[groupingTree]) T where T.RN = 1
> 
> TRUNCATE TABLE [dbo].[groupingTree]
> 
> INSERT INTO [dbo].[groupingTree] ( [GroupingId] ,[Code] ,[Description] ,[SortOrder] ) SELECT [GroupingId] ,[Code] ,[Description] ,[SortOrder] FROM #temp
> 
> DROP TABLE #temp

**Comment by bill-ramos-rmoswi** [comment]
This solution is ok. It all comes down to performance related to the size of your table and the indexes you have and test the performance. For example, if this was used as a staging table for loading into a data warehouse, the approach makes sense. You might want to have a index on the `[Code]` column to help with the performance of the `ROW_NUMBER()` function.

**Comment by JayakumarEMIS** [comment]
Sure Thanks @bill-ramos-rmoswi
