### ISSUE TITLE
Import data from excel file into table 

### ISSUE THREAD

**Issue by JayakumarEMIS** [bill-ramos-rmoswi/babelfish_postgresql_towel#7]
Hi @bill-ramos-rmoswi ,
 I am looking into below query not supporting into babelfish, basically this query we used for connecting Microsoft.ACE.OLEDB.12.0 provider. after connecting we import data from excel file into table,
 
MSSQL Query:
----------------
EXEC sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.12.0', N'AllowInProcess', 1				
				EXEC sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.12.0', N'DynamicParameters', 1	
				EXEC sp_addlinkedserver
				@server = N'TrudImportExcelDatabase',
				@provider = N'Microsoft.ACE.OLEDB.12.0',
				@srvproduct = N'Excel',
				@datasrc = @fileName,
				@provstr = N'Excel 12.0;IMEX=1;HDR=YES;'

INSERT INTO [dbo].[Student]
			   ([Code],
			    [Name])
		SELECT DISTINCT 
				[Code],
				[Name]
		FROM OPENQUERY(TrudImportExcelDatabase, 'SELECT * FROM [Contact Details$A6:ZZ]')

is there any solution to achieve the same functionality in babelfish?

**Comment by staticlibs** [comment]
@JayakumarEMIS Using MS Access provider in `sp_addlinkedserver` is not supported in Babelfish. I would suggest to load Excel files from client application, for example a separate C# application run by scheduler. XLSX format is straightforward to read from app code.

**Comment by JayakumarEMIS** [comment]
Thanks @staticlibs
