### ISSUE TITLE
Read file functionality not working in babelfish

### ISSUE THREAD

**Issue by JayakumarEMIS** [bill-ramos-rmoswi/babelfish_postgresql_towel#8]
Hi @bill-ramos-rmoswi,
trying to read xml file from my local path in babelfish, so i have write one below helper function in postgre and calling from babelfish t-sql, but got absolute path not allowed error while calling the function in babelfish t-sql, but it is working fine when I call the function from postgre sql itself, any idea about the issue or any idea to read xml file to local path?

postgre helper function:
----------------------------
CREATE OR REPLACE FUNCTION master_dbo.OPENXMLFile(
    filepath text
) RETURNS XML
LANGUAGE plpgsql
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
    RETURN pg_read_file(filepath):: xml;
END;
$BODY$;
 
ALTER FUNCTION master_dbo.OPENXMLFile(text) OWNER TO master_dbo;

Babelfish T-sql:
--------------------
SELECT master.dbo.openxmlfile('C:\Reconfigure\sample2.xml')

![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/153603497/60b36523-141f-4f6b-8ea7-7e4ef0d51291)

**Comment by bill-ramos-rmoswi** [comment]
Hi @JayakumarEMIS , try saving the function in the sys schema in the PG connection. Then grant permission to public.

**Comment by staticlibs** [comment]
@JayakumarEMIS I wonder if you can arrange the incoming files to be written to a subdirectory of `C:\Program Files\WiltonDB Software\wiltondb3.3\data` dir? If it is possible, then relative paths from data dir should work without using `pg_read_server_files` role (that may be undesired for security reasons).

**Comment by JayakumarEMIS** [comment]
> Hi @JayakumarEMIS , try saving the function in the sys schema in the PG connection. Then grant permission to public.

Hi @bill-ramos-rmoswi, I checked your suggestions for created the function under sys schema in postgre after grant pubic access to function but still get same issue, and I attached the can you look it, if I missing anything?

Function:
-----------
 
CREATE OR REPLACE FUNCTION sys.OPENXMLFile(
    filepath text
) RETURNS XML
LANGUAGE plpgsql
COST 100
VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
    RETURN pg_read_file(filepath):: xml;
END;
$BODY$;

Permission access:
-------------------
GRANT EXECUTE ON FUNCTION sys.OPENXMLFile(text) TO public;


Babelfish t-sql:
----------------
SELECT sys.openxmlfile(
	'C:\Reconfigure\sample2.xml'
)

![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/153603497/4b4760d3-98a2-487c-99b6-7ef589fa3986)

**Comment by JayakumarEMIS** [comment]
> @JayakumarEMIS I wonder if you can arrange the incoming files to be written to a subdirectory of `C:\Program Files\WiltonDB Software\wiltondb3.3\data` dir? If it is possible, then relative paths from data dir should work without using `pg_read_server_files` role (that may be undesired for security reasons).

Hi @staticlibs, if  place the file wilton db subdirectory location C:\Program Files\WiltonDB Software\wiltondb3.3\data I can able to get read it, but my scenario that not possible to move the file from original location to wilton db directory location, why because if we place any file inside the C:Programfiles directory the window user should have the admin access.

I tried  to gave pg_read_server_files role access as well to my user(wilton), but still not working. and my question is I can able to read the xml file while calling the below postgre custom helper function, inside babelfish postgre(5432)  but not able to do it babelfish tsql(1433)

Function:
CREATE OR REPLACE FUNCTION sys.OPENXMLFile(
filepath text
) RETURNS XML
LANGUAGE plpgsql
COST 100
VOLATILE PARALLEL UNSAFE
AS 

BEGIN
RETURN pg_read_file(filepath):: xml;
END;
;

Permission access:
GRANT EXECUTE ON FUNCTION sys.OPENXMLFile(text) TO public;

Babelfish Postgre: -> Working
SELECT master_dbo.openxmlfile(
	'C:\Reconfigure\sample2.xml'
)

![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/153603497/367592b1-0ecb-41a3-9e3f-923c87c4c805)


Babelfish t-sql: -> Not working
SELECT sys.openxmlfile(
'C:\Reconfigure\sample2.xml'
)

![image](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/153603497/820337d7-482c-4864-8552-9c95e9c8b8a1)

**Comment by bill-ramos-rmoswi** [comment]
Try @staticlibs suggestion of using the data directory.

**Comment by JayakumarEMIS** [comment]
> > @JayakumarEMIS I wonder if you can arrange the incoming files to be written to a subdirectory of `C:\Program Files\WiltonDB Software\wiltondb3.3\data` dir? If it is possible, then relative paths from data dir should work without using `pg_read_server_files` role (that may be undesired for security reasons).
> 
> Hi @staticlibs, if place the file wilton db subdirectory location C:\Program Files\WiltonDB Software\wiltondb3.3\data I can able to get read it, but my scenario that not possible to move the file from original location to wilton db directory location, why because if we place any file inside the C:Programfiles directory the window user should have the admin access.
> 
> I tried to gave pg_read_server_files role access as well to my user(wilton), but still not working. and my question is I can able to read the xml file while calling the below postgre custom helper function, inside babelfish postgre(5432) but not able to do it babelfish tsql(1433)
> 
> Function: CREATE OR REPLACE FUNCTION sys.OPENXMLFile( filepath text ) RETURNS XML LANGUAGE plpgsql COST 100 VOLATILE PARALLEL UNSAFE AS
> 
> BEGIN RETURN pg_read_file(filepath):: xml; END; ;
> 
> Permission access: GRANT EXECUTE ON FUNCTION sys.OPENXMLFile(text) TO public;
> 
> Babelfish Postgre: -> Working SELECT master_dbo.openxmlfile( 'C:\Reconfigure\sample2.xml' )
> 
> ![image](https://private-user-images.githubusercontent.com/153603497/347350913-367592b1-0ecb-41a3-9e3f-923c87c4c805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTYwMjQsIm5iZiI6MTcyMDYxNTcyNCwicGF0aCI6Ii8xNTM2MDM0OTcvMzQ3MzUwOTEzLTM2NzU5MmIxLTBlY2ItNDFhMy05ZTNmLTkyM2M4N2M0YzgwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMjQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmM1YWFmMzcxNmIwZGZlMWQxZTUyODBjNmNjYjM5YWIwNTk2MDM0OGViMGQ0YTMzMGZhMTM1YTRkNGRlMTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LCfsZXHj21zZmrXfyms0ih-YJCIwHMzYAqr3gBow5Nw)
> 
> Babelfish t-sql: -> Not working SELECT sys.openxmlfile( 'C:\Reconfigure\sample2.xml' )
> 
> ![image](https://private-user-images.githubusercontent.com/153603497/347351064-820337d7-482c-4864-8552-9c95e9c8b8a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTYwMjQsIm5iZiI6MTcyMDYxNTcyNCwicGF0aCI6Ii8xNTM2MDM0OTcvMzQ3MzUxMDY0LTgyMDMzN2Q3LTQ4MmMtNDg2NC04NTUyLTljOTVlOWM4YjhhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMFQxMjQ4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTBhNDJhNDc1ODBiODczMzJkODZhNDMyNDg2ZGQ1OTYyNTgxZjEzY2JiNWU4Yjg2MzhlNjI2NTZjZmFlZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.w_jNqvqu7HmdA0-ied5rB17B_Qmr5UjrNnSXVvWp6TE)

@bill-ramos-rmoswi  I tried @staticlibs suggestion that was working fine, but there will be an issue in some of our client systems don't have admin window user account, so it may cause the issue our customers, do you have any idea why absolute path not working in babelfish t-sql?

**Comment by staticlibs** [comment]
@JayakumarEMIS , would it be possible for you to set WiltonDB `log_directory` to some other dir outside of `Program Files`:

![log_directory](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/9497509/fd567040-836c-4401-9c27-b391cd2f4d4b)

And then create a writable directory underneath `log_directory` and give appropriate write/read permissions to such dir? This way `pg_read_file` will work on TDS connections with absolute paths to files under `log_directory`:

```tsql
select pg_read_file('C:\tmp\log\foo.txt')
```

If you need to set the specific dir permissions (or check effective access), default WiltonDB SCM account is [LocalService](https://learn.microsoft.com/en-us/windows/win32/services/localservice-account), its principal name is `Local Service`:

![log_directory_02](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/9497509/fea73b55-de5d-4114-a96f-b12f4d64f87d)
![log_directory_03](https://github.com/bill-ramos-rmoswi/babelfish_postgresql_towel/assets/9497509/8f7fd7b9-976e-4390-80ef-79b23e97fee5)

I will follow up on `pg_read_server_files` in Babelfish on TDS connections, but in general I suggest to not use it and use the setup above instead.

**Comment by JayakumarEMIS** [comment]
Hi @bill-ramos-rmoswi  and @staticlibs, I have added few modification in function to access file in pg_read_server_files in Babelfish on TDS connections, and that is working fine, using I can able to read file anywhere in local path. I think it would be helpful.

-- GRANT pg_read_server_files access to master_dbo
GRANT pg_read_server_files TO master_dbo;

-- Add secuity definer keyword during function creation
CREATE OR REPLACE FUNCTION master_dbo.openxmlfile(
	filepath text)
    RETURNS xml
    LANGUAGE 'plpgsql'
	SECURITY DEFINER
    COST 100
    VOLATILE PARALLEL UNSAFE
AS $BODY$
BEGIN
    RETURN pg_read_file(filepath):: xml;
END;
$BODY$;

GRANT EXECUTE ON FUNCTION master_dbo.openxmlfile(text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION  master_dbo.openxmlfile(text) TO master_dbo;

-- verify master_dbo have pg read file access
SELECT rolname
FROM pg_roles
WHERE rolname = 'master_dbo' AND pg_has_role('master_dbo', 'pg_read_server_files', 'member')


![image](https://github.com/user-attachments/assets/471aaa4c-8891-4f40-8fe1-b66c4ff38ef5)

**Comment by staticlibs** [comment]
@JayakumarEMIS , thanks for sharing the solution!

Basically, for `pg_read_server_files` permission to work it needs to be granted to the following role name (that depends on the current active T-SQL DB):

```tsql
select db_name() + '_' + current_user
```

Grant needs to be done on Postgres connection, after that `pg_read_file` will work on TDS connection.
