### ISSUE TITLE
Bulk Insert CSV not supporting in Babelfish

### ISSUE THREAD

**Issue by JayakumarEMIS** [bill-ramos-rmoswi/babelfish_postgresql_towel#9]
Hi @bill-ramos-rmoswi, I want to use bulk insert statement in bablefish, and it showing currently not supported so I am trying via achieve this in copy statement from postgre function and that was working fine for physical table, but my scenario i have to import data into temp table, can you please help me to acheive that?

T-SQL:
------------
BULK INSERT #temp
FROM 'C:\Reconfigure\log\tes.csv'
WITH
(
FIRSTROW = 1,
FIELDTERMINATOR = '|',  -- CSV field delimiter
ROWTERMINATOR = '\n',   -- Use to shift the control to next row
TABLOCK
);

![image](https://github.com/user-attachments/assets/f32564f9-87ca-4d5a-a610-a189d9ca2281)

**Comment by JayakumarEMIS** [comment]
Hi @staticlibs, I have written below one custom helper store procedure in postgre to achieve the bulk insert into temp table and return the temp, but it does not any table result, I shared the query can you help me what is the issue on it or do you have any query to extract data from csv into temp table?

CREATE OR REPLACE PROCEDURE master_dbo.import_csv(
	IN file_path text)
LANGUAGE 'plpgsql'
AS $BODY$
DECLARE
    inputString TEXT;
    headers TEXT;
    headerArray TEXT[];
    createTableQuery TEXT;
    columnDefinitions TEXT;
BEGIN
    -- Read the file into inputString
    inputString := pg_read_file(file_path);
    
    -- Replace carriage return and line feed with '\n'
    inputString := REPLACE(inputString, E'\r\n', E'\\n');
    
    -- Extract headers using string_to_array and array access
    headers := (string_to_array(inputString, E'\\'))[1];
    
    -- Convert headers into an array
    headerArray := string_to_array(headers, ',');
    
    -- Construct the column definitions
    columnDefinitions := '';
    FOR i IN array_lower(headerArray, 1) .. array_upper(headerArray, 1) LOOP
        columnDefinitions := columnDefinitions || headerArray[i] || ' TEXT';
        IF i < array_upper(headerArray, 1) THEN
            columnDefinitions := columnDefinitions || ', ';
        END IF;
    END LOOP;
    
    -- Construct the CREATE TABLE query
    createTableQuery := 'CREATE TEMPORARY TABLE temp_table (' || columnDefinitions || ');';
    
    -- Execute the CREATE TABLE query
    EXECUTE createTableQuery;
    
    -- Load the data from the CSV file into the temporary table
    EXECUTE 'COPY temp_table(' || headers || ') FROM ' || quote_literal(file_path) || ' DELIMITER '','' CSV HEADER';
	
    -- Select the data from the temporary table
     PERFORM * FROM temp_table;
    
    -- Drop the temporary table
    EXECUTE 'DROP TABLE temp_table';
END 
$BODY$;
ALTER PROCEDURE master_dbo.import_csv(text)
    OWNER TO wilton;

![image](https://github.com/user-attachments/assets/86960010-0664-4a1a-b4ab-b20c81a6d980)

I used perform to return the result but won't work

**Comment by JayakumarEMIS** [comment]
I have created the below function in postgre and call it from babelfish tsql connection and it is working fine for my scenario

Postgre:
---------------
CREATE OR REPLACE FUNCTION master_dbo.pscsystem_importproduct(
	file_path text,
	delimeter text)
    RETURNS void
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE SECURITY DEFINER PARALLEL UNSAFE
AS $BODY$
BEGIN
    -- Create a temporary table
    CREATE TEMPORARY TABLE IF NOT EXISTS temp_product(
       name VARCHAR(10)
    );
 
    -- Truncate the table if it already exists
    TRUNCATE temp_product;
 
    -- Import the CSV data into the temporary table
    EXECUTE 'COPY temp_product FROM ' || quote_literal(file_path) || ' DELIMITER ' || chr(39)|| delimeter || chr(39)||' CSV HEADER';

	   -- Grant permissions to the current user/role
    EXECUTE 'GRANT SELECT ON TABLE temp_product TO PUBLIC';
END;
$BODY$;

Babelfish t-sql
--------------------
EXEC master.dbo.pscsystem_importproduct @fileName, ',';
SELECT * FROM temp_product;

**Comment by staticlibs** [comment]
@JayakumarEMIS , thanks for sharing the solution! I think it is a good idea to do a select on T-SQL side.
